Web Scraping: Beautiful Soup

Fetches html content, beautiful soup makes a parse tree consisting of tags, we iterate through these tags fo fetch data

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [53]:
def get_data(pageno):
    url='https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_pg_'+str(pageno)+'_books?ie=UTF8&pg='+str(pageno)
    html=requests.get(url)
    soup=BeautifulSoup(html.content,'html.parser')
    data=[]
    for cell in soup.find_all('div',{'class':"zg-grid-general-faceout"}):
        book_name=cell.find('div',{'class':"_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y"})
        #print(book_name.text if book_name else 'NaN')#checked it works yay 
        #author_name=cell.find_all[1]('div',{'class':"_cDEzb_p13n-sc-css-line-clamp-1_1Fn1y"}) #this doesnt work with find, because the class is exactly the same as bookname. Now ill try to find some parent tag. OR use find_all 
        authorname=cell.find('div',{'class':"a-row a-size-small"})
        stars=cell.find('span',{'class':"a-icon-alt"})
        votes=cell.find('span',{'class':"a-size-small"})
        price=cell.find('span',{'class':"p13n-sc-price"}) #_cDEzb_p13n-sc-price_3mJ9Z price class was this removed dynamic part 
        #print(author_name.text if author_name else "NaN")
        #print(authorname.text if authorname else "NaN")
        #print(stars.text if stars else "NaN")
        #print(votes.text if votes else "NaN")
        #print(price.text if price else "NaN")
        book_link=cell.find('a',{'class':"a-link-normal aok-block"})
        #print('www.amazon.in'+book_link['href'] if book_link else 'Nan') # added www to add base url. href as anchor (a) doesnt have text. 
        data.append({'Book Name':book_name.text if book_name else 'NaN',
                     'Author Name':authorname.text if authorname else 'NaN',
                     'Ratings': stars.text if stars else 'NaN',
                     'Votes': votes.text if votes else 'NaN',
                     "Book_Link": 'www.amazon.in'+book_link['href'] if book_link else 'NaN'})
        #print(f"Star rating:{stars.text}\n Votes: {votes.text}\n Price:{price.text}") doesnt work 
    return data

In [55]:
data=get_data(1)
df=pd.DataFrame(data)
df
#soup.find('title').text #.text/.string= gives you text inside the html tag. Find= returns first occurence of a tag you want.   .
#soup.find_all('div') #find all gives all occurence. Find gives first occurence

,Book Name,Author Name,Ratings,Votes,Book_Link
0,My First Library Boxset For Kids (10 Board Boo...,Wonder House Books,4.5 out of 5 stars,"92,437",www.amazon.in/My-First-Library-Boxset-Board/dp...
1,PARMAR SSC Fatman | GK/GS Theory Book | Englis...,Parmar Sir,4.5 out of 5 stars,"1,031",www.amazon.in/PARMAR-English-Selection-Competi...
2,The Psychology of Money,Morgan Housel,4.6 out of 5 stars,"83,674",www.amazon.in/Psychology-Money-Morgan-Housel/d...
3,Maa Amma Anadha | మా అమ్మ అనాథ | Telugu Novel ...,GANA,5.0 out of 5 stars,1,www.amazon.in/Amma-Anadha-%E0%B0%85%E0%B0%AE%E...
4,White Nights by Fyodor Dostoyevsky: A Timeless...,Fyodor Dostoyevsky,4.6 out of 5 stars,"5,818",www.amazon.in/White-Nights-Penguin-Little-Clas...
5,"Atomic Habits: Tiny Changes, Remarkable Results",James Clear,4.6 out of 5 stars,"112,964",www.amazon.in/Atomic-Habits-James-Clear/dp/184...
6,My First Book of Patterns Pencil Control: Patt...,Wonder House Books,4.4 out of 5 stars,"33,971",www.amazon.in/First-Book-Patterns-Pencil-Contr...
7,The Mountain Is You: Transforming Self-Sabotag...,Brianna Wiest,4.5 out of 5 stars,"28,530",www.amazon.in/Mountain-You-Transforming-Self-S...
8,Jaun Elia: Ek Ajab Ghazab Shayar,Jaun Elia,4.5 out of 5 stars,"2,703",www.amazon.in/Jaun-Elia-Ajab-Ghazab-Shayar/dp/...
9,My First Library Set of 10 Board Books for Kid...,PW,4.5 out of 5 stars,"1,736",www.amazon.in/First-Library-Board-Books-Childr...
10,TUESDAYS WITH MORRIE (EXPORT) (A FORMAT),Mitch Albom,4.6 out of 5 stars,"38,393",www.amazon.in/TUESDAYS-MORRIE-EXPORT-FORMAT-Mi...
11,Metamorphosis,Franz Kafka,4.4 out of 5 stars,"17,460",www.amazon.in/Metamorphosis-Franz-Kafka/dp/817...
12,Blackbook of English vocabulary 2026 Edition (...,Nikhil Gupta,4.6 out of 5 stars,329,www.amazon.in/Blackbook-English-vocabulary-Med...
13,"SHNMN Sank Magic Practice Copybook, (4 BOOK +1...",QOKZEK,4.2 out of 5 stars,"5,794",www.amazon.in/Practice-Copybook-Preschoolers-c...
14,The Very Hungry Caterpillar,Eric Carle,4.7 out of 5 stars,"97,084",www.amazon.in/Very-Hungry-Caterpillar-Eric-Car...
15,You Can by George Matthew Adams | The Classic ...,George Matthew Adams,4.4 out of 5 stars,George Matthew Adams,www.amazon.in/Self-Belief-Self-Help-Motivation...
16,Arihant All in One Science (Exploration) Class...,Siddhartha Shankar,4.5 out of 5 stars,308,www.amazon.in/Exploration-Complete-Practice-Ex...
17,BRAHMASTRA Complete Maths Multicolored Formula...,Aditya Ranjan Sir,4.5 out of 5 stars,864,www.amazon.in/BRAHMASTRA-Complete-Multicolored...
18,Stop Letting Everything Affect You: How to bre...,Daniel Chidiac,4.6 out of 5 stars,"2,364",www.amazon.in/Stop-Letting-Everything-Affect-s...
19,201 Brain Booster Activity Book - Fun Activiti...,Wonder House Books,4.4 out of 5 stars,"3,661",www.amazon.in/201-Brain-Booster-Activity-Book/...
20,Meditations by Marcus Aurelius | Ancient Wisdo...,Marcus Aurelius,4.4 out of 5 stars,"5,765",www.amazon.in/Meditations-Marcus-Aurelius/dp/8...
21,"Courage To Be Disliked, The: How to free yours...",Ichiro Kishimi and Fumitake Koga,4.5 out of 5 stars,Ichiro Kishimi and Fumitake Koga,www.amazon.in/Courage-Be-Disliked-yourself-hap...
22,The Alchemist,Paulo Coelho,4.6 out of 5 stars,"181,972",www.amazon.in/Alchemist-Paulo-Coelho/dp/817223...
23,Ikigai: The Japanese secret to a long and happ...,Héctor García,4.6 out of 5 stars,"63,102",www.amazon.in/Ikigai-Japanese-Self-Help-Phenom...
24,The Power of Your Subconscious Mind: Original ...,Joseph Murphy,4.5 out of 5 stars,"67,701",www.amazon.in/Power-Your-Subconscious-Mind-Suc...
25,NCERT CLASS 9 Understanding Society – India an...,National council of educational research and t...,4.2 out of 5 stars,503,www.amazon.in/NCERT-CLASS-Understanding-Societ...
26,Oxford Student Atlas for India | For UPSC and ...,Oxford University Press,4.6 out of 5 stars,713,www.amazon.in/Oxford-Student-Atlas-India-Compe...
27,Sonia Gandhi,Sonia Gandhi,NaN,Sonia Gandhi,www.amazon.in/Belonging-Journey-Love-Sonia-Gan...
28,"Set of 10 Moral Story Books for Kids, Short Il...",PW expert,4.4 out of 5 stars,PW expert,www.amazon.in/Bedtime-Children-Colorful-Animat...
29,101 Pencil Control Activity Book For Kids | Tr...,Wonder House Books,4.4 out of 5 stars,"3,170",www.amazon.in/Pencil-Control-Activity-Book-Kid...
30,Psycho-Cybernetics (Updated and Expanded),Maxwell Maltz,4.6 out of 5 stars,"1,660",www.amazon.in/Psycho-Cybernetics-Updated-Expan...
31,Educart CBSE Class 10 Science Question Bank 20...,Prashant Kirad,4.4 out of 5 stars,467,www.amazon.in/Question-Chapterwise-Case-Based-...
32,Whisper In The Heart - The Ongoing Presence of...,Parvati Markus,4.8 out of 5 stars,278,www.amazon.in/Whisper-Heart-Devotional-literat...
33,Lucent's General Knowledge 2026 - English | Lu...,Dr. Binay Karna,4.3 out of 5 stars,460,www.amazon.in/Lucents-General-Knowledge-2026-C...
34,It’s Time to Say Goodnight,Wonder House Books,4.4 out of 5 stars,"2,242",www.amazon.in/ItS-Time-Goodnight-Eulalia-Rosa/...
35,Arihant All in One Social Science Class 10 for...,Jyoti Arora,4.6 out of 5 stars,Jyoti Arora,www.amazon.in/Arihant-Complete-Practice-Exerci...
36,Arihant All in One English Core Class 12 for C...,Kajaal Khanna,4.5 out of 5 stars,183,www.amazon.in/Arihant-Complete-Practice-Exerci...
37,Ayodhya Cherina Krishna - Telugu Novel,Srinivas Kamisetty,4.6 out of 5 stars,614,www.amazon.in/Ayodhya-Cherina-Krishna-Telugu-N...
38,Colouring Books | Pack Of 12 Copy Colour Books...,Wonder House Books,4.4 out of 5 stars,"6,997",www.amazon.in/Colouring-Books-Kids-Colour-Chil...
39,Yesteryear: The electrifying must-read debut –...,Caro Claire Burke,4.1 out of 5 stars,"114,471",www.amazon.in/Yesteryear-electrifying-must-rea...
40,Pearson 2026 UGC NET Paper 1 Teaching & Resear...,KVS Madaan,4.5 out of 5 stars,355,www.amazon.in/Teaching-Research-Aptitude-Quest...
41,"Indian Polity Courseware (English), 8e by M La...",M Laxmikanth,4.6 out of 5 stars,"1,629",www.amazon.in/Courseware-Laxmikanth-Conceptual...
42,Arihant All in One Social Science (Understandi...,Nazma Ansari,4.4 out of 5 stars,Nazma Ansari,www.amazon.in/Arihant-Social-Science-Understan...
43,NCERT CLASS 9 Iravati – Sanskrit R3 Textbook f...,National council of educational research and t...,3.0 out of 5 stars,2,www.amazon.in/NCERT-CLASS-Iravati-Sanskrit-202...
44,MTG NCERT at your FINGERTIPS Biology For NEET ...,MTG Editorial Board,4.6 out of 5 stars,"1,039",www.amazon.in/FINGERTIPS-Biology-2026-2027-Con...
45,Oswaal CBSE Class 10 Science Question Bank | C...,Oswaal Editorial Board,4.5 out of 5 stars,Oswaal Editorial Board,www.amazon.in/Science-Question-Topic-wise-2017...
46,Anxious People: The No. 1 New York Times bests...,Fredrik Backman,4.6 out of 5 stars,"91,405",www.amazon.in/Anxious-People-bestseller-author...
47,Arihant All in One Science Class 10 for CBSE E...,Alpesh Kumar,4.5 out of 5 stars,265,www.amazon.in/Arihant-Complete-Practice-Exerci...
48,Days at the Morisaki Bookshop: The perfect boo...,Satoshi Yagisawa,4.4 out of 5 stars,"13,852",www.amazon.in/Days-Morisaki-Bookshop-Internati...
49,Don't Believe Everything You Think (English),Joseph Nguyen,4.5 out of 5 stars,"18,168",www.amazon.in/Dont-Believe-Everything-You-Thin...

In [56]:
no_of_pages=2
all_data=[]
for pageno in range (1,no_of_pages+1):
    all_data.extend(get_data(pageno))

In [57]:
df=pd.DataFrame(all_data)
df

,Book Name,Author Name,Ratings,Votes,Book_Link
0,My First Library Boxset For Kids (10 Board Boo...,Wonder House Books,4.5 out of 5 stars,"92,437",www.amazon.in/My-First-Library-Boxset-Board/dp...
1,PARMAR SSC Fatman | GK/GS Theory Book | Englis...,Parmar Sir,4.5 out of 5 stars,"1,031",www.amazon.in/PARMAR-English-Selection-Competi...
2,The Psychology of Money,Morgan Housel,4.6 out of 5 stars,"83,674",www.amazon.in/Psychology-Money-Morgan-Housel/d...
3,Maa Amma Anadha | మా అమ్మ అనాథ | Telugu Novel ...,GANA,5.0 out of 5 stars,1,www.amazon.in/Amma-Anadha-%E0%B0%85%E0%B0%AE%E...
4,White Nights by Fyodor Dostoyevsky: A Timeless...,Fyodor Dostoyevsky,4.6 out of 5 stars,"5,818",www.amazon.in/White-Nights-Penguin-Little-Clas...
...,...,...,...,...,...
95,Man's Search For Meaning: The classic tribute ...,Viktor E Frankl,4.5 out of 5 stars,"98,727",www.amazon.in/Mans-Search-Meaning-Viktor-Frank...
96,Musafir Café,Divya Prakash Dubey,4.4 out of 5 stars,"3,979",www.amazon.in/Musafir-Cafe-Divya-Prakash-Dubey...
97,PW NEET Easy Handwritten Notes Inorganic Chemi...,Om Pandey,4.6 out of 5 stars,602,www.amazon.in/Handwritten-Inorganic-Chemistry-...
98,Mathematics Class 10 by R.D. Sharma | CBSE Exa...,R.d. Sharma,4.6 out of 5 stars,506,www.amazon.in/Mathematics-Preparation-Practice...
99,2000+ Dot Sticker Activity Book For 3+ Years O...,PW,4.3 out of 5 stars,148,www.amazon.in/Activity-Uppercase-Lowercase-Scr...