In [2]:
%run ./tmdbapi.ipynb

In [3]:
import requests
url='https://api.themoviedb.org/3/genre/movie/list?api_key='+API_key
response=requests.get(url)
response.json()

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [54]:
def get_data(pageno,year,genre):
  url='https://api.themoviedb.org/3/discover/movie?api_key='+API_key+'&primary_release_year.gte='+str(year)+'&sort_by=popularity.desc&with_genres='+str(genre)+'&page='+str(pageno)
  response=requests.get(url)
  if response.status_code==200:
    data=response.json()
    return data['results']
  else:
    return 'error'

In [55]:
import pandas as pd
df=pd.DataFrame(columns=['Movie ID','Movie Name'])

In [56]:
import time
pageno=1
while(len(df)<300):

  query_results=get_data(pageno,2000,35)
  if query_results !='error':
    for movie in query_results:
      df.loc[len(df)]=[movie['id'],movie['title']]

  pageno+=1
  time.sleep(0.25)

In [57]:
len(df['Movie ID'].unique())

253

In [8]:
def get_similar_movie(movieid):
  url='https://api.themoviedb.org/3/movie/'+str(movieid)+'/similar?api_key='+API_key
  response=requests.get(url)
  if response.status_code==200:
    return response.json()['results']
  else:
    return 'error'

In [9]:
get_similar_movie(1204680)

[{'adult': False,
  'backdrop_path': '/nv6F6tz7r61DUhE7zgHwLJFcTYp.jpg',
  'genre_ids': [35, 10749, 80],
  'id': 974635,
  'title': 'Hit Man',
  'original_language': 'en',
  'original_title': 'Hit Man',
  'overview': 'A mild-mannered professor moonlighting as a fake hit man in police stings ignites a chain reaction of trouble when he falls for a potential client.',
  'popularity': 14.3166,
  'poster_path': '/oil3EZwKFp3CWxZnfGfGglesvm9.jpg',
  'release_date': '2024-05-16',
  'softcore': False,
  'video': False,
  'vote_average': 6.78,
  'vote_count': 1740},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [35, 10749],
  'id': 192280,
  'title': "Helen's Marriage",
  'original_language': 'en',
  'original_title': "Helen's Marriage",
  'overview': 'Helen and Tom are desperate to get married. After a foiled elopement attempt, the couple hatches a “fake wedding” scheme to trick Helen’s protective parents into allowing their marriage.',
  'popularity': 0.8437,
  'poster_path': '/3OsfD2J7ySOK3IBEQNBftI6zsiT.jpg',
  'release_date': '1912-05-22',
  'softcore': False,
  'video': False,
  'vote_average': 4.9,
  'vote_count': 4},
 {'adult': False,
  'backdrop_path': '/gsLBOyzJQHEMTtFVNunAfVVPByT.jpg',
  'genre_ids': [35, 10751],
  'id': 192305,
  'title': 'Vacation of Petrov and Vasechkin, Usual and Incredible',
  'original_language': 'ru',
  'original_title': 'Каникулы Петрова и Васечкина, обыкновенные и невероятные',
  'overview': 'In the first part, the students complain that classic works of literature have no bearing on modern life - and find themselves in a situation strangely resembling something they\'ve read... It\'s Gogol\'s "Inspector General" - but set in a summer camp... In the second part, after reading Don Quixote, the ever-adventurous Vasechkin convinces more cautious Petrov that he has found a game that they could play for life. No sooner they go off than Vasechkin, on a bike, brandishing an umbrella, attacks a giant... That is, a windmill...',
  'popularity': 1.0549,
  'poster_path': '/q4e1CqpBPKkAkI4XZJF9DiviOKa.jpg',
  'release_date': '1984-10-28',
  'softcore': False,
  'video': False,
  'vote_average': 7.0,
  'vote_count': 23},
 {'adult': False,
  'backdrop_path': '/8oYykF1Qhrb8fC2qZqD71EzRywg.jpg',
  'genre_ids': [12, 10751, 14],
  'id': 278927,
  'title': 'The Jungle Book',
  'original_language': 'en',
  'original_title': 'The Jungle Book',
  'overview': 'After a threat from the tiger Shere Khan, Mowgli, a man-cub fostered by wolves, is forced to flee the jungle, and he embarks on a journey of self-discovery with the help of the panther, Bagheera, and the free-spirited bear, Baloo.',
  'popularity': 15.2395,
  'poster_path': '/2Epx7F9X7DrFptn4seqn4mzBVks.jpg',
  'release_date': '2016-04-07',
  'softcore': False,
  'video': False,
  'vote_average': 6.879,
  'vote_count': 8620},
 {'adult': False,
  'backdrop_path': '/g5EQiNuY71DguRWo1V4FBmTFQIM.jpg',
  'genre_ids': [35, 10751, 80],
  'id': 18943,
  'title': 'Ernest Goes to Jail',
  'original_language': 'en',
  'original_title': 'Ernest Goes to Jail',
  'overview': 'Bumbling bank janitor Ernest P. Worrell is assigned to jury duty, and soon finds himself in trouble when he is covertly switched with a look-a-like crime boss. Ernest must escape from jail to expose the mix-up.',
  'popularity': 3.6529,
  'poster_path': '/w1k8SgODFQOk9wHjX4mi8QdkYAO.jpg',
  'release_date': '1990-04-06',
  'softcore': False,
  'video': False,
  'vote_average': 5.036,
  'vote_count': 181},
 {'adult': False,
  'backdrop_path': '/iuRVt8tFiXDPGgzavhuSa3QHRxD.jpg',
  'genre_ids': [35],
  'id': 18785,
  'title': 'The Hangover',
  'original_language': 'en',
  'original_title': 'The Hangover',
  'overview': "When three friends finally come to after a raucous night of bachelor-party revelry, they find a baby in the closet and a tiger in the bathroom. But they can't seem to locate their best friend, Doug – who's supposed to be tying the knot. Launching a frantic search for Doug, the trio perseveres through a nasty hangover to try to make it to the church on time.",
  'popularity': 24.4302,
  'poster_path': '/A0uS9rHR56FeBtpjVki16M5xxSW.jpg',
  'release_date': '2009-06-02',
  'softcore': False,
  'video': False,
  'vote_average': 7.337,
  'vote_count': 18464},
 {'adult': False,
  'backdrop_path': '/rflNo8MqOQnkyA4aplRweprlwwe.jpg',
  'genre_ids': [18, 35, 27, 9648, 53],
  'id': 18910,
  'title': 'The Ninth Configuration',
  'original_language': 'en',
  'original_title': 'The Ninth Configuration',
  'overview': "Army psychiatrist Colonel Kane is posted to a secluded gothic castle housing a military asylum. With a reserved calm, he indulges the inmates' delusions, allowing them free rein to express their fantasies.",
  'popularity': 2.4282,
  'poster_path': '/jlQMBckfnLhiCusar62sJ7WCKBv.jpg',
  'release_date': '1980-02-29',
  'softcore': False,
  'video': False,
  'vote_average': 6.4,
  'vote_count': 175},
 {'adult': False,
  'backdrop_path': '/qNpmWT0K7EzOQq9cBoyjTKWJWXZ.jpg',
  'genre_ids': [35, 10751],
  'id': 19084,
  'title': 'Johnson Family Vacation',
  'original_language': 'en',
  'original_title': 'Johnson Family Vacation',
  'overview': 'Nate Johnson, a Los Angeles man estranged from his wife and three children, decides to reconnect with his family by taking them with him on a road trip to Missouri for a big family reunion.',
  'popularity': 3.6817,
  'poster_path': '/3F6bmetJSJvqLCB9PMxpNz1sngB.jpg',
  'release_date': '2004-04-07',
  'softcore': False,
  'video': False,
  'vote_average': 5.509,
  'vote_count': 212},
 {'adult': False,
  'backdrop_path': '/gpAGraW59m8PSweLbThQrdlS94B.jpg',
  'genre_ids': [28, 12, 80, 53],
  'id': 19108,
  'title': 'Breaker! Breaker!',
  'original_language': 'en',
  'original_title': 'Breaker! Breaker!',
  'overview': 'Truck driver searches for his brother, who has disappeared in a town run by a corrupt judge.',
  'popularity': 3.853,
  'poster_path': '/gfYp4WG1l4uk5eoUf3Iqe3knwZY.jpg',
  'release_date': '1977-04-01',
  'softcore': False,
  'video': False,
  'vote_average': 5.0,
  'vote_count': 96},
 {'adult': False,
  'backdrop_path': '/iTgjBD4EkeA3Ra86E1X47vgREO7.jpg',
  'genre_ids': [35, 18, 9648, 53],
  'id': 18408,
  'title': 'Cherish',
  'original_language': 'en',
  'original_title': 'Cherish',
  'overview': 'After a martini-induced rampage, a fantasy-prone young woman is placed under house arrest.',
  'popularity': 1.3733,
  'poster_path': '/hTNAKGnqi8v4FRPEjm9Wl5S5yMz.jpg',
  'release_date': '2002-01-17',
  'softcore': False,
  'video': False,
  'vote_average': 6.047,
  'vote_count': 43},
 {'adult': False,
  'backdrop_path': '/mvRPZXCHfsn7UoUI1TvjX0MqqWG.jpg',
  'genre_ids': [35, 10770],
  'id': 278943,
  'title': 'Jury Duty: The Comedy',
  'original_language': 'en',
  'original_title': 'Jury Duty: The Comedy',
  'overview': "Mild and meek accountant Sanford Lagelfost has been charged with embezzling $3 million dollars from Trout Industries. A decidedly mixed bag of jurors are chosen to serve on the case, including Eddie, a waiter; Rita, a high-priced call girl; Phil, a high-powered businessman; and Abby, a rabble rousing ex-hippie. When the star witness, the voluptuous Hope Hathaway, takes the stand, she startles everyone with her stories of Sanford's Lothario-esque conquests. Suddenly, the unassuming Sanford is a celebrity heartthrob and he finds himself in headlines and gossip columns across the country. Due to the case's growing notoriety, the judge sequesters the jury. And things start to get wild...",
  'popularity': 0.9741,
  'poster_path': '/2tmodSUFQ7e2vJwGz5VvGEosr9E.jpg',
  'release_date': '1990-01-14',
  'softcore': False,
  'video': False,
  'vote_average': 2.5,
  'vote_count': 4},
 {'adult': False,
  'backdrop_path': '/yXybBEC45p84D0Ky7GmQQYrclVr.jpg',
  'genre_ids': [28, 12, 14],
  'id': 447404,
  'title': 'Pokémon Detective Pikachu',
  'original_language': 'en',
  'original_title': 'Pokémon Detective Pikachu',
  'overview': 'In a world where people collect pocket-size monsters (Pokémon) to do battle, a boy comes across an intelligent monster who seeks to be a detective.',
  'popularity': 20.3142,
  'poster_path': '/uhWvnFgg3BNlcUz0Re1HfQqIcCD.jpg',
  'release_date': '2019-05-03',
  'softcore': False,
  'video': False,
  'vote_average': 6.897,
  'vote_count': 7500},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [35],
  'id': 265366,
  'title': 'Swedish Wife Exchange Club',
  'original_language': 'de',
  'original_title': 'Ehepaar sucht gleichgesinntes',
  'overview': 'The young, married Marianne falls into the circles of partner swapping. Georg, her husband, accuses her of frigidity and uptightness. After an argument in the marital bedroom, they separate and divorce. Marianne soon meets Franz and his wife Judith, who need a certain stimulant to achieve complete satisfaction. Marianne is the perfect object for them.',
  'popularity': 0.9806,
  'poster_path': '/kklEhF950oyLk8FtCfRWkcpg5eQ.jpg',
  'release_date': '1969-11-28',
  'softcore': False,
  'video': False,
  'vote_average': 3.0,
  'vote_count': 5},
 {'adult': False,
  'backdrop_path': '/hoItQR25BE6qWLInEq1iRPgBDDZ.jpg',
  'genre_ids': [14, 16, 35, 10751],
  'id': 11114,
  'title': "Pete's Dragon",
  'original_language': 'en',
  'original_title': "Pete's Dragon",
  'overview': "Pete, a young orphan, runs away to a Maine fishing town with his best friend a lovable, sometimes invisible dragon named Elliott! When they are taken in by a kind lighthouse keeper, Nora, and her father, Elliott's prank playing lands them in big trouble. Then, when crooked salesmen try to capture Elliott for their own gain, Pete must attempt a daring rescue.",
  'popularity': 4.7459,
  'poster_path': '/noShGNQKAgMqNanJL5EiZlf6LCp.jpg',
  'release_date': '1977-11-03',
  'softcore': False,
  'video': False,
  'vote_average': 6.318,
  'vote_count': 735},
 {'adult': False,
  'backdrop_path': '/oxQJT3CCwxRRDgnPUZvT6xmts61.jpg',
  'genre_ids': [28, 35],
  'id': 11230,
  'title': 'Drunken Master',
  'original_language': 'cn',
  'original_title': '醉拳',
  'overview': 'After getting into trouble, a mischievous young man is sent to train under a brutal, but slovenly old beggar, who teaches him the secret of the Drunken Fist.',
  'popularity': 11.3726,
  'poster_path': '/cf43J2SH8tECZVl9N5n0Q6Ckche.jpg',
  'release_date': '1978-10-05',
  'softcore': False,
  'video': False,
  'vote_average': 7.392,
  'vote_count': 1163},
 {'adult': False,
  'backdrop_path': '/kgqgbPB2snzVlkMkQjYAvmF1hkc.jpg',
  'genre_ids': [28, 18, 10751, 12],
  'id': 11231,
  'title': 'The Next Karate Kid',
  'original_language': 'en',
  'original_title': 'The Next Karate Kid',
  'overview': "Mr. Miyagi decides to take Julie, a troubled teenager, under his wing after he learns that she blames herself for her parents' demise and struggles to adjust with her grandmother and fellow pupils.",
  'popularity': 6.6354,
  'poster_path': '/wI3gCi9w1cuUJCiwhviAy46we9Q.jpg',
  'release_date': '1994-07-18',
  'softcore': False,
  'video': False,
  'vote_average': 5.399,
  'vote_count': 1203},
 {'adult': False,
  'backdrop_path': '/2vwdO2ist8YgKg60p4N7S8Hwd0A.jpg',
  'genre_ids': [12, 35],
  'id': 11418,
  'title': "National Lampoon's European Vacation",
  'original_language': 'en',
  'original_title': "National Lampoon's European Vacation",
  'overview': "The Griswolds win a vacation to Europe on a game show, and so pack their bags for the continent. They do their best to catch the flavor of Europe, but they just don't know how to be be good tourists. Besides, they have trouble taking holidays in countries where they CAN speak the language.",
  'popularity': 4.956,
  'poster_path': '/hZL7g1oSDrA0Lx5wcHpEl99MYKi.jpg',
  'release_date': '1985-07-25',
  'softcore': False,
  'video': False,
  'vote_average': 6.166,
  'vote_count': 1037},
 {'adult': False,
  'backdrop_path': '/sAHFU3OW7TBTJq82kfiAYm0hUeK.jpg',
  'genre_ids': [35, 28],
  'id': 1402825,
  'title': 'Jungle Jim and the Goblin Empire',
  'original_language': 'en',
  'original_title': 'Jungle Jim and the Goblin Empire',
  'overview': 'Jungle Jim and his superhero friends must defeat the goblin empire to retrieve the Sacred Sword',
  'popularity': 0.4894,
  'poster_path': '/vSjry4ThXWDjmBw84GRLS1W1IYG.jpg',
  'release_date': '2024-06-21',
  'softcore': False,
  'video': False,
  'vote_average': 7.0,
  'vote_count': 1},
 {'adult': False,
  'backdrop_path': None,
  'genre_ids': [27, 35],
  'id': 1582280,
  'title': 'Double Jump',
  'original_language': 'en',
  'original_title': 'Double Jump',
  'overview': 'Things happen to Hank McManson during his biggest meeting yet…',
  'popularity': 0.8337,
  'poster_path': '/rd4G2NwgulRbxUu9vhtBxTpfGAi.jpg',
  'release_date': '2024-11-27',
  'softcore': False,
  'video': False,
  'vote_average': 10.0,
  'vote_count': 1},
 {'adult': False,
  'backdrop_path': '/hvMbN6oWjXo2pv3c8IpfkFetvtX.jpg',
  'genre_ids': [35, 878],
  'id': 11285,
  'title': 'Cocoon: The Return',
  'original_language': 'en',
  'original_title': 'Cocoon: The Return',
  'overview': 'The reinvigorated elderly group that left Earth comes back to visit their relatives. Will they all decide to go back to the planet where no one grows old, or will they be tempted to remain on Earth?',
  'popularity': 3.3381,
  'poster_path': '/xBsXdBl8qCXoQsWX6vfsVjWOMGk.jpg',
  'release_date': '1988-09-13',
  'softcore': False,
  'video': False,
  'vote_average': 6.465,
  'vote_count': 1033}]

In [10]:
df1=pd.DataFrame(columns=['Movie ID','Similar Movie ID'])
for movieid in df['Movie ID']:
  query_results=get_similar_movie(movieid)
  if query_results!='error':
    for i in range(min(5,len(query_results))):
      df1.loc[len(df1)]=[movieid,query_results[i]['id']]

In [11]:
df1.head(10)

   Movie ID  Similar Movie ID
0   1204680            974635
1   1204680            192280
2   1204680            192305
3   1204680            278927
4   1204680             18943
5   1393326            601083
6   1393326            601099
7   1393326            974626
8   1393326           1368494
9   1393326            595143

In [58]:
def get_imdb_id(movieid):
  url='https://api.themoviedb.org/3/movie/'+str(movieid)+'/external_ids?api_key='+str(API_key)
  response=requests.get(url)
  if response.status_code==200:
    return response.json()
  else:
    return 'error'

In [59]:
get_imdb_id(1204680)

{'id': 1204680,
 'imdb_id': 'tt1756855',
 'wikidata_id': 'Q106392679',
 'facebook_id': 'coyoteacmemovie',
 'instagram_id': 'coyoteacmemovie',
 'twitter_id': 'CoyoteACMEMovie'}

In [60]:
df['IMDB_ID']=None

In [61]:
for i,movieid in enumerate(df['Movie ID']):
  query_results=get_imdb_id(movieid)
  if query_results!='error':
    df.loc[i,'IMDB_ID']=query_results['imdb_id']

In [62]:
IMDB_data=pd.read_csv('/content/title.ratings.tsv',sep='\t')

In [63]:
df=df.merge(IMDB_data,how='left',left_on='IMDB_ID',right_on='tconst')

In [64]:
df['IMDB_URL']='https://www.imdb.com/title/'+df['IMDB_ID'].fillna(' ')+'/'

In [65]:
df

,Movie ID,Movie Name,IMDB_ID,tconst,averageRating,numVotes,IMDB_URL
0,1204680,Coyote vs. Acme,tt1756855,tt1756855,7.6,13354.0,https://www.imdb.com/title/tt1756855/
1,1393326,Ghost in the Cell,tt9000310,tt9000310,6.7,2604.0,https://www.imdb.com/title/tt9000310/
2,1137844,Mayday,tt28014327,tt28014327,6.9,3388.0,https://www.imdb.com/title/tt28014327/
3,1084244,Toy Story 5,tt29355505,tt29355505,7.4,77768.0,https://www.imdb.com/title/tt29355505/
4,1315772,Minions & Monsters,tt32890033,tt32890033,6.3,30236.0,https://www.imdb.com/title/tt32890033/
...,...,...,...,...,...,...,...
295,49524,R.I.P.D.,tt0790736,tt0790736,5.6,152602.0,https://www.imdb.com/title/tt0790736/
296,19908,Zombieland,tt1156398,tt1156398,7.5,673782.0,https://www.imdb.com/title/tt1156398/
297,585511,Luck,tt7214954,tt7214954,6.5,36302.0,https://www.imdb.com/title/tt7214954/
298,840430,The Holdovers,tt14849194,tt14849194,7.9,273438.0,https://www.imdb.com/title/tt14849194/
299,1245993,Caught Stealing,tt1493274,tt1493274,6.8,89976.0,https://www.imdb.com/title/tt1493274/

In [66]:
df.rename(columns={'averageRating':'IMDB_Ratings','numVotes':'IMDB Votes'},inplace=True)
df.drop('tconst',axis=1)

,Movie ID,Movie Name,IMDB_ID,IMDB_Ratings,IMDB Votes,IMDB_URL
0,1204680,Coyote vs. Acme,tt1756855,7.6,13354.0,https://www.imdb.com/title/tt1756855/
1,1393326,Ghost in the Cell,tt9000310,6.7,2604.0,https://www.imdb.com/title/tt9000310/
2,1137844,Mayday,tt28014327,6.9,3388.0,https://www.imdb.com/title/tt28014327/
3,1084244,Toy Story 5,tt29355505,7.4,77768.0,https://www.imdb.com/title/tt29355505/
4,1315772,Minions & Monsters,tt32890033,6.3,30236.0,https://www.imdb.com/title/tt32890033/
...,...,...,...,...,...,...
295,49524,R.I.P.D.,tt0790736,5.6,152602.0,https://www.imdb.com/title/tt0790736/
296,19908,Zombieland,tt1156398,7.5,673782.0,https://www.imdb.com/title/tt1156398/
297,585511,Luck,tt7214954,6.5,36302.0,https://www.imdb.com/title/tt7214954/
298,840430,The Holdovers,tt14849194,7.9,273438.0,https://www.imdb.com/title/tt14849194/
299,1245993,Caught Stealing,tt1493274,6.8,89976.0,https://www.imdb.com/title/tt1493274/

In [21]:
df

,Movie ID,Movie Name,IMDB_ID,tconst,IMDB_Ratings,IMDB Votes,IMDB_URL
0,1204680,Coyote vs. Acme,tt1756855,tt1756855,7.6,13354,https://www.imdb.com/title/tt1756855/
1,1393326,Ghost in the Cell,tt9000310,tt9000310,6.7,2604,https://www.imdb.com/title/tt9000310/
2,1137844,Mayday,tt28014327,tt28014327,6.9,3388,https://www.imdb.com/title/tt28014327/
3,1084244,Toy Story 5,tt29355505,tt29355505,7.4,77768,https://www.imdb.com/title/tt29355505/
4,1315772,Minions & Monsters,tt32890033,tt32890033,6.3,30236,https://www.imdb.com/title/tt32890033/
...,...,...,...,...,...,...,...
295,533535,Deadpool & Wolverine,tt6263850,tt6263850,7.5,592107,https://www.imdb.com/title/tt6263850/
296,862,Toy Story,tt0114709,tt0114709,8.3,1197298,https://www.imdb.com/title/tt0114709/
297,1612018,Jackass: Best and Last,tt39316472,tt39316472,6.2,11797,https://www.imdb.com/title/tt39316472/
298,1327819,Hoppers,tt26443616,tt26443616,7.2,83956,https://www.imdb.com/title/tt26443616/
299,552524,Lilo & Stitch,tt11655566,tt11655566,6.7,98365,https://www.imdb.com/title/tt11655566/