In [34]:
import pandas as pd
import numpy as np

In [35]:
df=pd.read_csv("data/user_data.csv") # relative to Feature Extraction/, run the notebook from there

In [36]:
df.shape

(100000, 4)

In [37]:
R=df.pivot_table(index='user_id', columns='movie_id',values='rating',fill_value=0)

In [38]:
R.shape

(943, 1682)

In [39]:
values, vectors=np.linalg.eigh(R.T@R) #claude when to use eigh and when to use eig?
index=np.argsort(values)[::-1]
vectors=vectors[:,index]
V=vectors[:,:50]
values=values[index]
S=np.maximum(np.sqrt(values),0)[:50]
U=(R@V)/S

C:\Users\chaud\AppData\Local\Temp\ipykernel_14136\3142626916.py:6: RuntimeWarning: invalid value encountered in sqrt
  S=np.maximum(np.sqrt(values),0)[:50]

In [40]:
R_low=U@np.diag(S)@V.T
R_low

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
user_id,,,,,,,,,,,,,,,,,,,,,
1,6.448389,2.950450,1.625981,3.045275,1.647414,1.677801,3.665330,0.230101,1.581494,3.362219,...,0.044845,-0.048244,-0.043236,-0.028824,0.040667,-0.002204,-0.006613,-0.004409,0.007978,0.053666
2,2.334278,0.115586,-0.101178,0.309950,0.149196,0.478109,0.206328,0.125428,1.868183,0.670484,...,0.021613,-0.005844,-0.017532,-0.011688,-0.009124,0.003119,0.009356,0.006237,0.030368,-0.028043
3,0.327603,-0.273722,-0.143939,-0.157102,0.021782,-0.057236,-0.042934,0.501579,-0.041899,0.263806,...,-0.014133,-0.021162,0.057255,0.038170,-0.008297,0.015429,0.046287,0.030858,0.006647,0.002022
4,0.382688,-0.435003,0.044126,0.005795,0.064509,-0.078957,0.300215,-0.034386,-0.117565,-0.121150,...,0.004029,-0.004515,-0.016469,-0.010979,0.010426,0.006779,0.020338,0.013559,-0.001440,-0.025620
5,4.266469,1.925990,0.052194,1.085306,0.669737,0.030129,1.739678,0.829531,0.297069,0.595196,...,0.009230,-0.070531,-0.029523,-0.019682,-0.052096,-0.001925,-0.005775,-0.003850,-0.032994,-0.011765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,1.564051,-0.120189,-0.203935,-0.219531,0.345003,0.143898,-0.131293,1.117403,2.952719,-0.205779,...,0.015247,-0.003047,0.049542,0.033028,0.039737,-0.003818,-0.011455,-0.007637,0.036453,-0.032913
940,0.581881,-0.351892,-0.189681,2.146662,0.445512,0.001521,3.114317,2.617950,2.550968,-0.474921,...,0.007572,0.032456,0.003001,0.002001,0.019280,0.005035,0.015105,0.010070,-0.019198,-0.052545
941,3.096936,-0.040443,0.542198,-0.057696,-0.172614,0.000640,2.344081,0.436471,0.667862,-0.006161,...,-0.016700,-0.012349,-0.047474,-0.031650,-0.004616,-0.001018,-0.003053,-0.002035,-0.004124,-0.013163
942,0.954203,0.599508,0.484349,-0.333945,0.476189,0.198800,-0.262425,1.327533,-0.582840,-0.740371,...,0.015548,0.032979,0.037874,0.025250,-0.013767,0.005931,0.017794,0.011863,0.019777,0.002097
943,1.415023,2.858034,1.780059,1.833960,1.068232,0.341622,1.310728,-0.057049,1.847871,-0.596195,...,0.038449,-0.078411,-0.066360,-0.044240,0.008657,-0.008690,-0.026071,-0.017380,0.011628,0.046363

In [41]:
def recommendation(user_id,topn):
    user_index=R.index.get_loc(user_id)
    scores=R_low.iloc[user_index]
    scores[(R.iloc[user_index]>0).to_numpy()]=np.inf
    sorted_indices=np.argsort(scores)[::-1]
    top_indices= sorted_indices[:topn]
    recommendation=pd.DataFrame({'movie_id':R.columns[top_indices],'scores':scores[top_indices]})

    return recommendation

In [42]:
recommendation(1,10)

     movie_id  scores
16         17     inf
0           1     inf
271       272     inf
270       271     inf
269       270     inf
268       269     inf
267       268     inf
266       267     inf
265       266     inf
264       265     inf